#!/bin/bash

dpkg-reconfigure tzdata
dpkg-reconfigure locales
chmod +x update; /root/update;
apt-get install -y software-properties-common

add-apt-repository ppa:ondrej/apache2
add-apt-repository ppa:ondrej/php
/root/update

apt-get install -y apache2 libapache2-mod-php8.1 php8.1-fpm bash-completion zip unzip curl wget vim screen imagemagick redis memcached mysql-server apache2 fuse snapd build-essential git sendmail jpegoptim optipng php8.1-mysql php8.1-mbstring php8.1-mcrypt php8.1-memcached php8.1-redis php8.1-apcu php8.1-gd php8.1-imagick php8.1-bcmath php8.1-curl php8.1-memcache php8.1-dev php8.1-zip php8.1-tidy php8.1-ssh2 php8.1-xml php8.1-xmlrpc

a2enmod proxy_fcgi setenvif cache deflate expires headers filter http2 ext_filter rewrite ssl socache_shmcb;
a2enconf php8.1-fpm
systemctl restart apache2

snap install core
snap refresh core
snap install --classic certbot
ln -s /snap/bin/certbot /usr/bin/certbot

mysql_secure_installation

wget https://wordpress.org/latest.zip
